### ISSUE TITLE
Can I use the library with "offline" image? 

### ISSUE THREAD

**Issue by romshiri** [Fotoapparat/FaceDetector#10]
Hi,

I'd like to run face(s) detection in a given image (that was selected from the image gallery for example).

1. Can I do it?
2. Can it support multiple faces in a given image?

**Comment by dmitry-zaitsev** [comment]
1. Yes.
2. Yes.

The library does not require Internet connection or Play Services.

**Comment by romshiri** [comment]
Hi @dmitry-zaitsev, thanks for the answer.
I see that the function named "detectFaces" should receive an image in NV21 format.
As I said, I'd like to run face detection on a simple image that was loaded from the photos gallery.

How do I convert the image (which is basically just a path for a local image), into an NV21 bytes array?
I don't have any experience with image processing etc, so perhaps you can help me with your experience.

**Comment by Diolor** [comment]
Hi @romshiri . Did you search stackoverflow? [There are several answers there ](https://www.google.de/search?q=stackoverflow+convert+image+to+NV21&oq=stackoverflow+convert+image+to+NV21&aqs=chrome..69i57j69i64.7435j0j4&sourceid=chrome&ie=UTF-8)
