### ISSUE TITLE
Error compiling app, because you have 2 times declared uses-permission

### ISSUE THREAD

**Issue by gabrielmartinez** [Fotoapparat/FaceDetector#12]
`<uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="18"/>
    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE"
        android:maxSdkVersion="18"/>`

**Comment by Diolor** [comment]
what's your compilation error? Permissions are different

**Comment by gabrielmartinez** [comment]
When I try to upload the app to Google, google says that those permisions are duplicated, y research yersterday and could be, that you need to put "minSdkVersion" today I will download the project to build and try to put the minSdkVersion to test and I will share the results with you.

**Comment by JiamingWu233** [comment]
@gabrielmartinez 
I had the same problem
Solution:
In the project manifest
<use -permission android:name="android. Permission. WRITE_EXTERNAL_STORAGE "tools: node="replace"/>
<use -permission android:name="android. Permission. READ_EXTERNAL_STORAGE "tools: node="replace"/>
Reference: https://developer.android.com/studio/build/manifest-merge.html

**Comment by gabrielmartinez** [comment]
Thank's @JiamingWu233
