### ISSUE TITLE
open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by xieqiupeng** [Fotoapparat/FaceDetector#13]
compile this module,and add it in my project, then have this problem.
open failed: EACCES (Permission denied)
i can not access any file in my android phone.

**Comment by Diolor** [comment]
https://stackoverflow.com/questions/8854359/exception-open-failed-eacces-permission-denied-on-android

**Comment by xieqiupeng** [comment]
i have added the permission, the project source url is 
https://github.com/xieqiupeng/ali_face_recognition_demo
if u have time to pull it,please help me look at that, thank you.

**Comment by Diolor** [comment]
hey, the link gets a 404
