### ISSUE TITLE
How to extrat faces when detected?

### ISSUE THREAD

**Issue by Solony** [Fotoapparat/FaceDetector#14]
Hello, I found your work and it was amazing. I'm developing such app as well, just out of curiosity.
Now everything works perfectly and I want to know to to extract peoples' faces when detected?
For example I know detected 3 people in one image and I want to classify their faces based on different labels. My first attempt was to look into what exactly was in faces list but I could understand a thing.
Hopefully you may give me some decent ideas. Thank you!

**Comment by dmitry-zaitsev** [comment]
Faces list just contains rectangles of the faces on the image. You would then need to crop those rectangle out of the full image in order to do recognition.

**Comment by Solony** [comment]
Thank you. I think I found a way.
