### ISSUE TITLE
when added to gradle it put a MAX SDK 

### ISSUE THREAD

**Issue by defaultbr** [Fotoapparat/FaceDetector#2]
but when this library is added at my app gradle the manifest became this:

```
 <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="18" />
    <uses-permission
        android:name="android.permission.READ_EXTERNAL_STORAGE"
        android:maxSdkVersion="18" />
```

maxSdkVersion added by FaceDetector

the maxSdkVersion is not necessary for me, since most of all my users use sdk 19+

**Comment by defaultbr** [comment]
https://github.com/Fotoapparat/FaceDetector/blob/master/Android/facedetector/src/main/AndroidManifest.xml


maxSdkVersion should be removed, is there any reason for this?!

**Comment by dmitry-zaitsev** [comment]
`android:maxSdkVersion` in the context of `uses-permission` means that this permission is required only for devices which are using API level 18 or lower. It is not the same as maxSdkVersion which limits the maximum API version on which app can run.

**Comment by defaultbr** [comment]
I understood, the question is: all my devices when i add this library remove the READ/WRITE external storage permission, so i cant give it to the device (Apps -> MyApp -> Permissions) it disappear from the list

**Comment by Diolor** [comment]
Actually that right. `android:maxSdkVersion="18"` will be added in the merged Manifest. So if you need to use `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>` this will break the app on 19+ SDKs when trying access non-app files

**Comment by dmitry-zaitsev** [comment]
You can also use manifest merger options to force your app to overrule library's flags: https://developer.android.com/studio/build/manifest-merge.html
