### ISSUE TITLE
OPENCV_HOME

### ISSUE THREAD

**Issue by kangdawei** [Fotoapparat/FaceDetector#20]
Could not get unknown property 'OPENCV_HOME' for object of type com.android.build.gradle.internal.dsl.ExternalNativeCmakeOptions.

**Comment by dmitry-zaitsev** [comment]
You need to define the path to the OpenCV home directory inside your `local.properties` or global Gradle properties.

That's how it looks like for me:

```
OPENCV_HOME=/Users/Dmitry/OpenCV-android-sdk
```
