### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by sevar83** [Fotoapparat/FaceDetector#22]
Hi, thanks for this state-of-the-art library. That's not an issue but just a few questions.
- What problems I'd possibly face if I try to develop an iOS module on top of Core?
- Is it possible to use the GPU acceleration with OpenCL and UMat instead of Mat?

**Comment by dmitry-zaitsev** [comment]
Hi @sevar83 , 

- There should not be any big problems with iOS. I worked with similar set up in one of my previous companies and it was working generally fine. There might be a small change required here and there to make the compiler happy but no more than that.
- I _think_ it is possible, but to be honest I never tried that. Do you experience any performance problems with current implementation?

**Comment by sevar83** [comment]
I plan to create a realtime OCR module and possibly the image processing pipeline will be too heavy for mobile CPU in realtime. So, I consider using GPU but I've just found out that iOS doesn't support OpenCL but uses their Metal API and OpenCV has OpenCL / CUDA and no Metal support. I will try without GPU at first.

**Comment by dmitry-zaitsev** [comment]
I would recommend instead focusing on reducing the text detection area as much as possible. For example, coming up with your own text detection implementation (such as SWT) which is optimised for your needs. If you are using Tesseract that would speed up the process significantly as the default text detection is rather faulty and slow.

**Comment by sevar83** [comment]
Yeah, I would expect good bounds detection will help for better results. But my use case is scanning watch backplates where the texts are simple numbers but they are curved, very tiny and sometimes there are reflections.
